Add F-4E Phantom to the list of CAS/STRIKE capable planes
dcs-liberation/dcs_liberation pull request #1073
Opened 2021-05-10 23:24 UTC by Hornet2041

#1072 

 adds F-4E to list of CAS and STRIKE capable missions

2021-05-10 23:55 UTC, DanAlbert requested changes

2021-05-10 23:55 UTC, DanAlbert commented on gen/flights/ai_flight_planner_db.py
> +    F_4E,
These are a priority order, so putting it here means that the F-4 will be preferred for CAS over the F/A-18. I don't think that was your intent. Probably makes more sense below the Harrier?

2021-05-10 23:55 UTC, DanAlbert commented on gen/flights/ai_flight_planner_db.py
> +    F_4E,
Ditto.

2021-05-11 00:47 UTC, Hornet2041 commented
oh very cool, hadn't realized that was a priority order. I stuck them lower on the list since its an older aircraft and can only carry rockeyes, mk82/84/gbu-12/10 and rockets

2021-05-11 01:14 UTC, DanAlbert approved these changes
Looks good now, thanks!

2021-05-11 01:14 UTC, merged