fixed AttributeError for AircraftType capability
dcs-liberation/dcs_liberation pull request #1282
Opened 2021-06-19 21:37 UTC by RndName

carrier_capable and lha_capable were throwing attribute errors. Maybe the problem sits in the `aircrafttype.py` as normaly it should (if i understand it correctly - sorry not so much time to analyze it into detail) init with False if it does not exists.

@DanAlbert

2021-06-19 21:59 UTC, DanAlbert requested changes
This is hiding a more serious bug, I think.

2021-06-19 22:01 UTC, DanAlbert commented
> This is hiding a more serious bug, I think.

Yes, the problem is that some places in the UI didn't get fixed to use the new type. The airfield selectors are wrong. I'll push a fix.

2021-06-19 22:03 UTC, DanAlbert commented
Actually that seems to have been just an annotation issue. All the callsites look fine. I haven't seen this so I can't investigate it further myself.

2021-06-20 03:27 UTC, DanAlbert commented
e09f53da8f939a61c8b053b6752df08a308c4481

2021-06-20 03:27 UTC, closed without merging

2021-06-20 07:07 UTC, RndName commented
Awesome! Great one :) i tested it with my save and it works like a charm