Allow player to delay start of friendly ground forces' advance on front line
dcs-liberation/dcs_liberation pull request #1383
Opened 2021-06-28 18:53 UTC by nosv1

Implements https://github.com/dcs-liberation/dcs_liberation/issues/964

*eek... first gameplay PR*

So yeh, as the issue above suggests, an ability to delay the front line. As it is currently implemented, this does not consider the stance, but simply if the front line is delayed it is set to reach Waypoint 1 at the delayed time (Waypoint 1 is like a couple of feet in front of waypoint 0, so not really sure how the AI handles having WP 1 being a set time while still spawning in on mission start).

I think that's it really... I never did test an actual mission, but the ME showed everything as expected.

The delayed start should be getting reset to 0 after each turn.

![image](https://user-images.githubusercontent.com/47610393/123688617-d982af80-d817-11eb-8dfa-50f4337aff84.png)
![image](https://user-images.githubusercontent.com/47610393/123688801-16e73d00-d818-11eb-91f0-d7d2d0692dc3.png)
![image](https://user-images.githubusercontent.com/47610393/123688812-1babf100-d818-11eb-9a87-78c2c4b86ba0.png)

it's the ground speed of 0 that has me worried for WP 1

2021-06-30 19:45 UTC, bgreman commented
Reopening after inadvertent branch deletion

2021-07-01 02:54 UTC, DanAlbert requested changes

2021-07-01 02:54 UTC, DanAlbert commented on game/theater/controlpoint.py
> +        self.delayed_start: timedelta = timedelta(seconds=0)
It looks like you're creating a `QTimeEdit` per front but only a delay per base. The most recently set time will clobber the others for a multi-front base.

2021-07-01 02:54 UTC, DanAlbert commented on gen/armor.py
> +                    pass
A better way to do this is with `__setstate__`. There are examples of how to do it elsewhere in the codebase.

2021-07-01 02:54 UTC, DanAlbert commented on gen/armor.py
> +                    dcs_group.points[1].speed_locked = False
The fact that WP1 _must_ be close to WP0 for this to work is a really easy thing to overlook for anyone that might be altering front line behavior. Instead, create a wait action with an end time like we do for hold points for air units?

2021-07-01 02:54 UTC, DanAlbert commented on qt_ui/windows/basemenu/ground_forces/QGroundForcesStrategy.py
> +                    "Forces will not move from Waypoint 1 until the specified time has elapsed."
Players don't know what waypoint 1 is (I didn't until I saw the screenshot in this PR).

2021-07-01 02:54 UTC, DanAlbert commented on qt_ui/windows/basemenu/ground_forces/QGroundForcesStrategy.py
> +        self.cp.delayed_start = timedelta(seconds=seconds)
```suggestion
        self.cp.delayed_start = timedelta(hours=time.hour(), minutes=time.minute(), seconds=time.second())
```

2022-01-13 01:36 UTC, DanAlbert commented
Closing stale PRs for clarity. They're trivial to reopen if you want to return to this :)

2022-01-13 01:36 UTC, closed without merging