Client start option
dcs-liberation/dcs_liberation pull request #1674
Opened 2021-10-23 10:12 UTC by MetalStormGhost

Added a new settings option: Default start type for Player aircraft. Refactored to use the new StartType enum from game.ato.starttype. Resolves #1567 but also allows other start types for Player flights besides hot start.

2021-10-23 19:08 UTC, DanAlbert requested changes

2021-10-23 19:08 UTC, DanAlbert commented on game/commander/packagebuilder.py
> +            flight.start_type = self.settings.default_start_type_client
Probably safer to add a separate `player_start_type` field to the `Flight` constructor so it can deal with this internally rather than needing to remember to do this in every location? Does mean that `Flight` needs to also get the `Settings` object but that's probably going to be true sooner or later anyway.

2021-10-23 19:08 UTC, DanAlbert commented on qt_ui/windows/mission/flight/QFlightCreator.py
> +            StartType(self.start_type.currentText()),
Instead of doing this, you can add values to the combo box:

```
for start_type in StartType:
    self.start_type.addItem(start_type.value, start_type)
```

And then use `self.start_type.currentData()` instead.

2021-10-23 19:08 UTC, DanAlbert commented on qt_ui/windows/mission/flight/QFlightCreator.py
> +                self.start_type.setCurrentIndex(i)
Don't do this IMO. If they player has manually set this field we shouldn't be resetting it just because they added or removed a pilot (especially because adding more slots might add pilots unintentionally).

Could add yet another "default start type for manually created flights" as well if that's workload reducing, but I think the main value of the client default is in making the auto ATO more auto.

2021-10-23 19:08 UTC, DanAlbert commented on qt_ui/windows/mission/flight/settings/QFlightStartType.py
> +        self.package_model.update_tot()
Same.

2021-10-23 19:26 UTC, MetalStormGhost commented on qt_ui/windows/mission/flight/QFlightCreator.py
> +                self.start_type.setCurrentIndex(i)
How about I add a flag if the user has manually set this field? I could then use the flag to prevent resetting their changes.

2021-10-23 19:48 UTC, MetalStormGhost commented on game/commander/packagebuilder.py
> +            flight.start_type = self.settings.default_start_type_client
I tried to do that but I ran into a very nasty looking circular import problem...

2021-10-23 19:51 UTC, DanAlbert commented on qt_ui/windows/mission/flight/QFlightCreator.py
> +                self.start_type.setCurrentIndex(i)
Maybe it would be better to replace `Flight.start_type: StartType` with `Flight.custom_start_type: Optional[StartType]`, and the UI can instead show "Default (Cold)" or whatever, and the default type can be resolved as-needed? The advantage would be that the UI code and behavior is better, plus changing the settings can have an effect _this turn_ instead of next turn. The downside is that means that any time someone alters that setting every package TOT needs to be re-evaluated (the ASAP ones of course, but also all the others because switching from hot to cold might make early takeoffs suddenly be negative).

The trouble with the flag in the UI is that it's only in the UI so if you close and open the window it no longer knows if the start type was an explicit choice or not. Storing that UI specific data in the save game is... gross.

I think I still like my original idea best for the time being. It's the simplest and I suspect it's more than enough to solve the problem.

2021-10-23 20:30 UTC, MetalStormGhost commented on qt_ui/windows/mission/flight/QFlightCreator.py
> +                self.start_type.setCurrentIndex(i)
I could try your approach of showing "Default (Cold)" etc, especially now since we have that new StartType class. I assume iterating over all flights and updating their TOT is trivial, but I haven't tried it out yet.

2021-10-23 23:57 UTC, DanAlbert commented on qt_ui/windows/mission/flight/QFlightCreator.py
> +                self.start_type.setCurrentIndex(i)
I should probably mention that some things I have planned for 6 or 7 will make this obsolete anyway, so the simple answer is going to be the right answer.

2021-10-25 16:29 UTC, MetalStormGhost commented on game/commander/packagebuilder.py
> +            flight.start_type = self.settings.default_start_type_client
@DanAlbert Could I ask for your help with getting Settings object access in Flight?

2022-02-03 13:54 UTC, RndName commented
Is this PR still maintained?

2022-02-03 18:02 UTC, MetalStormGhost commented
> Is this PR still maintained?

I ran into a circular import problem when trying to access the new setting for client start option in the Flight object. I stopped working on it at that time, but I could clean this up and complete this if I could get that circular import figured out. If this was C++, I'd have already done this months ago.

Having spent the time learning how the dependencies work with Liberation, I could take another look at this.

2022-02-03 20:04 UTC, DanAlbert commented
I don't think there's any point in doing so. Like I said, this is going to be obsolete soon anyway because start type won't exist once turns are gone

2022-02-06 22:49 UTC, closed without merging