Carrier type selection
dcs-liberation/dcs_liberation pull request #1787
Opened 2021-11-22 22:20 UTC by MetalStormGhost

Added an alternate way to define carriers in the faction file:
  "carriers": {
    "Forrestal": [
      "CV-59 Forrestal",
      "CV-60 Saratoga",
      "CV-61 Ranger",
      "CV-62 Independence"
    ],
    "Stennis": [
      "CVN-71 Theodore Roosevelt",
      "CVN-72 Abraham Lincoln",
      "CVN-73 George Washington",
      "CVN-74 John C. Stennis",
      "CVN-75 Harry S. Truman"
    ]
  },

The carrier names are picked based on the carrier type. Several carriers can be included in the same campaign with names coming from different pools. Also prevented duplicate names in campaigns with more than one carrier.

If the carriers are not found in the faction file with this new format, Liberation falls back to the previous method. This retains compatibility with existing faction files.

Also added support for defining preferred carrier types and carrier names in the campaign yaml:
carriers:
  Blue CV-1:
    preferred_name: CVN-74 John C. Stennis
    preferred_type: Stennis
  Blue CV-2:
    preferred_name: CV-60 Saratoga
    preferred_type: Forrestal

Resolves #1699

2022-01-02 23:03 UTC, DanAlbert commented
Reviewing design only for now, avoiding the code until I have a handle on the plan.

The change to the faction file is unnecessary, right? The important piece in the faction is that it's possible to spawn some Nimitz class, Forrestal class, Kuznetsov class, etc carrier, but the specific model doesn't really matter, right? Are you trying to enable factions that for some reason can use the Roosevelt but not the Truman? If that is the goal, why the hierarchy? Probably better to add unit data yaml for carriers like we did for ground and air units and let those define the upgrade/downgrade paths and variants. The faction file could list the variants it can use instead of needing to copy/paste the hierarchy into every faction.

```
  Blue CV-1:
    preferred_name: CVN-74 John C. Stennis
    preferred_type: Stennis
```

What does this actually mean? If the player chooses to enable super carrier, does this do nothing? That's probably fine, just want to make sure I understand the intent here before digging into the code.

The goals here, I think, are:

1. Allow campaign designers to pick a specific carrier to fit their campaign's narrative, with fallbacks if it's unavailable to the faction or player settings
2. Continue allowing players to enable/disable supercarrier as needed mid-game
3. Keep the carrier name/skin consistent between turns as long as the supercarrier option remains consistent
4. Allow players to choose their own carrier type at campaign creation time in the new game wizard

Is that right?

2022-01-03 07:51 UTC, MetalStormGhost commented
> The change to the faction file is unnecessary, right? The important piece in the faction is that it's possible to spawn some Nimitz class, Forrestal class, Kuznetsov class, etc carrier, but the specific model doesn't really matter, right? Are you trying to enable factions that for some reason can use the Roosevelt but not the Truman? If that is the goal, why the hierarchy? Probably better to add unit data yaml for carriers like we did for ground and air units and let those define the upgrade/downgrade paths and variants. The faction file could list the variants it can use instead of needing to copy/paste the hierarchy into every faction.

The change to the faction file is only needed if more than one carrier types are used by a faction. If there is only one type of carrier, the old format still works, so we don't lose backwards compatibility with existing faction files. No copy-pasting needed.

The specific model of carrier matters when the campaign has aircraft which can only take off from one type of carrier but not the other. For example, flying a carrier based campaign in multiplayer with friends who only have the FC3 module. The Su-33 will need its own carrier which needs to be STOBAR and the US CATOBAR aircraft cannot take off from it.

A side-effect of this is that it's possible to define factions which have the Roosevelt but not the Truman, which we would probably do in an Operation Desert Storm faction. Similarly, the Desert Storm faction would probably have Forrestal class carriers which would need to have their own name.

> 
> ```
>   Blue CV-1:
>     preferred_name: CVN-74 John C. Stennis
>     preferred_type: Stennis
> ```
> 
> What does this actually mean? If the player chooses to enable super carrier, does this do nothing? That's probably fine, just want to make sure I understand the intent here before digging into the code.

If the player enables supercarrier, then they will end up with a Theodore Roosevelt called "CVN-74 John C. Stennis".

2022-01-03 07:54 UTC, MetalStormGhost commented
> The goals here, I think, are:
> 
>     1. Allow campaign designers to pick a specific carrier to fit their campaign's narrative, with fallbacks if it's unavailable to the faction or player settings
> 
>     2. Continue allowing players to enable/disable supercarrier as needed mid-game
> 
>     3. Keep the carrier name/skin consistent between turns as long as the supercarrier option remains consistent
> 
>     4. Allow players to choose their own carrier type at campaign creation time in the new game wizard
> 
> 
> Is that right?

The goals here are mainly:

1. Allow factions to have more than one type of carrier, with individual names for the different types.

2. Have the possibility to define in the campaign which carrier is which, in case the carrier air wings are not interchangeable.

3. Continue allowing players to enable/disable supercarrier as needed mid-game

I haven't considered any fallbacks to the carrier types apart from still supporting all existing factions and campaigns. If the new carrier types/names are not defined in the faction or campaign, it still works exactly as before. I think the fallbacks, upgrade/downgrade paths and variants need a separate PR and some additional design. I mainly used the discussion on #1699 to guide the design here.

Allowing players to choose their own carrier type at campaign creation time in the new game wizard is a good idea. I think it needs some more sketching up before starting implementation and a new PR.

2022-01-16 21:39 UTC, DanAlbert commented
> The change to the faction file is only needed if more than one carrier types are used by a faction. If there is only one type of carrier, the old format still works, so we don't lose backwards compatibility with existing faction files. No copy-pasting needed.
>
> The specific model of carrier matters when the campaign has aircraft which can only take off from one type of carrier but not the other. For example, flying a carrier based campaign in multiplayer with friends who only have the FC3 module. The Su-33 will need its own carrier which needs to be STOBAR and the US CATOBAR aircraft cannot take off from it.

But why is any of this the _faction's_ concern? The faction definition can say:

```json
  "carriers": [
    "CV-59 Forrestal",
    "CV-60 Saratoga",
    "CV-61 Ranger",
    "CV-62 Independence"
    "CVN-71 Theodore Roosevelt",
    "CVN-72 Abraham Lincoln",
    "CVN-73 George Washington",
    "CVN-74 John C. Stennis",
    "CVN-75 Harry S. Truman"
  ],
```

Each of those names would have an entry in `resources/units/carriers/` that specified what type of carrier those were. Maybe not this, but something like:

stennis.yaml:

```yaml
---
name: CVN-74 John C. Stennis
unit: Stennis
class: Nimitz
upgrade: CVN_75
```

truman.yaml:

```yaml
---
name: CVN-75 Harry S. Truman
unit: CVN_75
class: Nimitz
downgrade: Stennis
```

(`Nimitz` here would be part of a `CarrierClass` enum that we maintain that would also have things like `Forrestal` and `Kuznetsov`; it's there only to support the campaign author picking a preferred class when the exact type is not found)

If the campaign finds a name match in the faction, it uses that. If it doesn't but finds something of the same class, it uses that.

Only the `UnitData` object gets stored in the save game. When the mission is generated the supercarrier setting gets checked against the carrier data. The upgrade/downgrade path would be followed based on that option for selecting the unit ID, but the name would be whatever was previously selected. If the campaign selected a Truman but the player doesn't have supercarrier, it'll still be named the Truman throughout, it'll just spawn a Stennis in the mission.

> I think the fallbacks, upgrade/downgrade paths and variants need a separate PR and some additional design

Not having an upgrade/downgrade path is a regression. If you want to split this (I will always encourage smaller PRs, so you have my support on that), do the backend work with `UnitData` and whatnot _first_, and then tackle the campaign spec. I think the discrete steps you could separate here if you wanted are:

1. Add unit data.
2. Replace the TGO implementation's `Group` with the `UnitData` so we're not storing `Stennis` and `Forrestal` objects in the TGO.
3. Change the faction spec to refer to carriers by name only (my example above).
4. Add the campaign support.

I don't actually care if those are 4 PRs, but I do think it's important that step 4 happens last and not first. Even if we end up at the same place, doing 4 first creates a lot of _user visible_ churn.

lmk if I've misunderstood anything, but I'm pretty sure that covers all the use cases.

2022-01-16 21:44 UTC, DanAlbert requested changes
(marking changes requested so it leaves my review queue, if you re-request review from me in the UI after responded it'll come back)

2022-02-03 13:57 UTC, RndName commented
> > The change to the faction file is only needed if more than one carrier types are used by a faction. If there is only one type of carrier, the old format still works, so we don't lose backwards compatibility with existing faction files. No copy-pasting needed.
> > The specific model of carrier matters when the campaign has aircraft which can only take off from one type of carrier but not the other. For example, flying a carrier based campaign in multiplayer with friends who only have the FC3 module. The Su-33 will need its own carrier which needs to be STOBAR and the US CATOBAR aircraft cannot take off from it.
> 
> But why is any of this the _faction's_ concern? The faction definition can say:
> 
> ```json
>   "carriers": [
>     "CV-59 Forrestal",
>     "CV-60 Saratoga",
>     "CV-61 Ranger",
>     "CV-62 Independence"
>     "CVN-71 Theodore Roosevelt",
>     "CVN-72 Abraham Lincoln",
>     "CVN-73 George Washington",
>     "CVN-74 John C. Stennis",
>     "CVN-75 Harry S. Truman"
>   ],
> ```
> 
> Each of those names would have an entry in `resources/units/carriers/` that specified what type of carrier those were. Maybe not this, but something like:
> 
> stennis.yaml:
> 
> ```yaml
> ---
> name: CVN-74 John C. Stennis
> unit: Stennis
> class: Nimitz
> upgrade: CVN_75
> ```
> 
> truman.yaml:
> 
> ```yaml
> ---
> name: CVN-75 Harry S. Truman
> unit: CVN_75
> class: Nimitz
> downgrade: Stennis
> ```
> 
> (`Nimitz` here would be part of a `CarrierClass` enum that we maintain that would also have things like `Forrestal` and `Kuznetsov`; it's there only to support the campaign author picking a preferred class when the exact type is not found)
> 
> If the campaign finds a name match in the faction, it uses that. If it doesn't but finds something of the same class, it uses that.
> 
> Only the `UnitData` object gets stored in the save game. When the mission is generated the supercarrier setting gets checked against the carrier data. The upgrade/downgrade path would be followed based on that option for selecting the unit ID, but the name would be whatever was previously selected. If the campaign selected a Truman but the player doesn't have supercarrier, it'll still be named the Truman throughout, it'll just spawn a Stennis in the mission.
> 
> > I think the fallbacks, upgrade/downgrade paths and variants need a separate PR and some additional design
> 
> Not having an upgrade/downgrade path is a regression. If you want to split this (I will always encourage smaller PRs, so you have my support on that), do the backend work with `UnitData` and whatnot _first_, and then tackle the campaign spec. I think the discrete steps you could separate here if you wanted are:
> 
>     1. Add unit data.
> 
>     2. Replace the TGO implementation's `Group` with the `UnitData` so we're not storing `Stennis` and `Forrestal` objects in the TGO.
> 
>     3. Change the faction spec to refer to carriers by name only (my example above).
> 
>     4. Add the campaign support.
> 
> 
> I don't actually care if those are 4 PRs, but I do think it's important that step 4 happens last and not first. Even if we end up at the same place, doing 4 first creates a lot of _user visible_ churn.
> 
> lmk if I've misunderstood anything, but I'm pretty sure that covers all the use cases.

Some important info on this one:
I added all the Naval Unit Types with the GroundObject Refactoring and the Template system. There is also a UnitClass "AircraftCarrier" and "HelicopterCarrier" already. Additionally there will be only a "naval_units" list for the faction file which holds all possible units.
So adding only the specific things to the yaml files will be more easier than ever.

2022-04-01 06:56 UTC, closed without merging