Helipad spawn fallback at Airport control point
dcs-liberation/dcs_liberation pull request #1893
Opened 2022-01-01 11:48 UTC by MetalStormGhost

Implemented a fallback to _generate_at_airport() in case a "Not enough helipads available" situation is encountered at an Airfield control point. Also generates air starts over OffMapSpawn control points now.

Resolves #1890

2022-01-01 21:42 UTC, DanAlbert requested changes
Until they count as parking I don't think we should be using them _at all_ for airfields. Helipads should only get used at FARPs. The fallback just makes it easier for bugs in parking allocation to go unnoticed.

2022-01-12 08:21 UTC, MetalStormGhost commented
@Khopa Was helipad/FARP support at airfield control points intended? I'd be hesitant to remove the support unless it was added as an unintended side effect.

2022-01-12 08:42 UTC, Khopa commented
Yes I intended to make it possible to add additional helos slots on airport , but I did not extensively tested the feature and I think there were a few issues with it.
With the current version, I think it'd be better to just add a FARP not too far from the airfield, and just put the helos squadrons there.

2022-01-12 09:50 UTC, DanAlbert commented
> Yes I intended to make it possible to add additional helos slots on airport

Currently you can add them, but they don't count as additional parking. I think before I broke this more helicopters could spawn there, but there wasn't much reason to because it didn't free up a parking spot for a jet, nor would it allow them to operate off the helipads when the runway was down.

> so they don't block the runway for dozens of minutes

I think we could post-process (post so it doesn't interfere with parking assignments) each airfield to change helicopters from warm/runway starts to ground starts and accomplish the same thing without campaign designers needing to fix it by hand.

2022-01-12 10:38 UTC, MetalStormGhost commented
> I think we could post-process (post so it doesn't interfere with parking assignments) each airfield to change helicopters from warm/runway starts to ground starts and accomplish the same thing without campaign designers needing to fix it by hand.

I can do that in this PR.

> Currently you can add them, but they don't count as additional parking. I think before I broke this more helicopters could spawn there, but there wasn't much reason to because it didn't free up a parking spot for a jet, nor would it allow them to operate off the helipads when the runway was down.

Long-term (beyond the scope of this PR), any objections to me separating the parking (to a degree, at least)? I was thinking that we could have helicopters-only parking at airfields and helicopters could use either the helipads or the fixed-wing parking spots?

2022-01-12 17:34 UTC, DanAlbert commented
> I can do that in this PR.

Separate PR please.

> Long-term (beyond the scope of this PR), any objections to me separating the parking (to a degree, at least)? I was thinking that we could have helicopters-only parking at airfields and helicopters could use either the helipads or the fixed-wing parking spots?

No, that's what I'm pushing for: don't make this change until that's done.

2022-01-17 19:44 UTC, closed without merging