Add support for Eurogamer and Rafale mod aircraft
dcs-liberation/dcs_liberation pull request #2007
Opened 2022-02-09 22:04 UTC by angelatthetomb

Edited db.py, faction.py, start_generator.py, ai_flight_generator.py, qmodsettings.py, qnewgamegenerator.py. Added eurofighter.py and rafale.py. Added squadrons and custom loadouts. Tested in my forked build and work in-game.

2022-02-10 20:53 UTC, Khopa approved these changes

2022-02-10 20:54 UTC, Khopa commented
Hello, 

Thanks, the code changes looks good :)

However, i'm unsure which mod version is being used, can you confirm if it's these one : 

- Rafale : https://forums.eagle.ru/topic/252774-rafales-pack-new-version-005-for-279-by-the-cuesta-brothers/
- EuroFighter : https://forums.eagle.ru/topic/290086-new-version-eurofighter-typhoon-by-lechuzas-negras-v105/

2022-02-10 21:42 UTC, Khopa commented
💹 I've been able to test it succesfully with the Typhoon mod.

Just two things : 
* UI icons are missing
* There are no default factions allowing the use of the mod.

![image](https://user-images.githubusercontent.com/2546901/153500279-9320b09b-8dca-48dd-a6df-b600b30ac70e.png)

Could you add some for the modded planes ? (in resources/ui/aircrafts/icons)
Should be named {aircraft_class_id}_24.jpg and be a 91x24 jpeg.

Example for Typhoon: 
![Eurofighter_24](https://user-images.githubusercontent.com/2546901/153500126-5310eca5-56aa-4e40-9c59-88c441f4aeef.jpg)

(My process to produce these icons is just to screenshoot them in game, and resize in an image editor)

***

- If you want me to add the icons and default factions, i'll merge your PR and add them.
- However, if you want to do it, you can push the additional icons and factions files to this PR

2022-02-11 03:46 UTC, angelatthetomb commented
Hey Khopa,

I'll get some icons and a faction added to the pull request here in the next day or two. Thanks!

2022-02-12 22:06 UTC, Hornet2041 commented
Um, your commits also say they add the VSN Prowler and F/A-18F.

2022-02-12 22:25 UTC, Hornet2041 commented
> 

![image](https://user-images.githubusercontent.com/55866858/153730500-d9058316-f22b-49f0-ad70-f9c197ba7a8d.png)
Downloaded your latest build and got that error on trying to launch a new game.

2022-02-13 10:56 UTC, RndName requested changes
As already mentionend by @Hornet2041 there are unrelated mods coming in as well which are not mentionend in this PR. Please clean this one up.
Also it's kinda broken as the EA-6B and FA-18F will not be removed from the plane map when the mod is not checked.

2022-02-13 10:56 UTC, RndName commented on game/db.py
> +plane_map["FA18F_hornetAG"] = VSN_FA18F_AG
Neither EA-6B nor VSN_FA18F / AG are mentioned in this PR.

2022-02-13 10:56 UTC, RndName commented on game/factions/faction.py
>          if not mod_settings.su57_felon:
Forgot to handle the EA-6B and FA-18F.

2022-02-13 11:40 UTC, RndName commented on resources/factions/bluefor_modern_2015.json
> +  "name": "Bluefor Modern 2015",
Why a new faction? And this one is formatted quite wrong. A lot of indents are not right.

2022-02-13 21:14 UTC, angelatthetomb commented
Hey guys, sorry about the EA6B and FA18 references, I committed to the wrong fork. Those are in my next project.

For now, I've got this PR back to the correct commit, and from there I added icons for the Rafale B and C and the Eurofighter. I also added them to the "Bluefor Modern" faction.

2022-02-18 20:57 UTC, DanAlbert commented on game/db.py
> +plane_map["Eurofighter"] = Eurofighter
This ugly system was just redone. Instead, decorate mod classes with `@planemod` and be sure to add an `import` in `pydcs_extensions.__init__`. Have a look at other mods for examples.

2022-04-19 08:21 UTC, RndName commented
PR got stale, any further changes planned or shall we close this one?

2022-06-30 07:09 UTC, DanAlbert commented
We're closing stale PRs. If this is still needed, please update and reopen.

2022-06-30 07:09 UTC, closed without merging