Patch 4
dcs-liberation/dcs_liberation pull request #3340
Opened 2024-02-12 23:31 UTC by Chilli935

- Corrected banner file types.
- Corrected australia_2005.yaml and usn_2005.yaml
- Added australia_2009.yaml and usn_2009.yaml

2024-03-03 04:19 UTC, zhexu14 requested changes
@Chilli935 , a few things I've noticed playing around with this PR. I was mostly looking at it from the perspective of someone who doesn't have the mod installed. It would be good if you could have a play with this build to check it works as expected for someone who does have the mod. If something doesn't work and you're stuck, let me know. 

BTW, not sure how familiar you are with Github, but in case you didn't know, you can download the build of Liberation with this PR included from the Checks tab of this PR. You'll need to select the "build" action (left hand menu) and download the Artefact (top right).

Lastly, does this PR supersede this one https://github.com/dcs-liberation/dcs_liberation/pull/3338? If so, I'll go ahead and close that one.

2024-03-03 04:19 UTC, zhexu14 commented on resources/units/aircraft/EA-18G.yaml
> +  SEAD: 600
One field that Liberation has which Retribution doesn't support is a `hit_points` which helps with tracking deaths. Does this mod have a custom damage model?  Sorry --  I'm not familiar with the Superhornet mod. If it uses the DCS Lot 20 hornet damage model, IIRC that has 20 hit points.

2024-03-03 04:19 UTC, zhexu14 commented on resources/units/aircraft/EA-18G.yaml
> +tasks:
Should the SEAD Escort mission type also be supported by the Growler?

2024-03-03 04:19 UTC, zhexu14 commented on qt_ui/windows/newgame/QNewGameWizard.py
> +        self.registerField("fa18efg", fa18efg)
This will mean the mod will be called "fa18efg" in the New Game Wizard , which I assume is not what you intended?
![Screenshot 2024-03-03 090549](https://github.com/dcs-liberation/dcs_liberation/assets/64713351/aa3f4906-982a-4727-a22c-3faf60ea64ed)

2024-03-03 04:19 UTC, zhexu14 commented on resources/factions/usn_2009.yaml
> +name: US Navy 2005
The name should be "US Navy 2009"

2024-03-03 04:19 UTC, zhexu14 commented on resources/factions/australia_2009.yaml
> +liveries_overrides: []
If you don't need this element, just delete it. Currently, this factions file is broken in the sense that Liberation cannot load it correctly and it doesn't show up in the New Game Wizard.

2024-03-03 04:19 UTC, zhexu14 commented on resources/ui/units/aircrafts/banners/FA-18E.jpg
- All other banners are 720 x 360 pixels so would be good to stick to that.
- The icons for the modded units are not showing up, probably because the images in the `icons` folder are .png files instead of .jpg files.

 ![Screenshot 2024-03-03 092248](https://github.com/dcs-liberation/dcs_liberation/assets/64713351/388e3be8-c395-48ef-b64a-cbc8e3a9ba96)

2024-03-04 12:16 UTC, Chilli935 commented
> @Chilli935 , a few things I've noticed playing around with this PR. I was mostly looking at it from the perspective of someone who doesn't have the mod installed. It would be good if you could have a play with this build to check it works as expected for someone who does have the mod. If something doesn't work and you're stuck, let me know.

I have tested it with the mod installed as someone who owns the module and others that don't and it worked good for us. The AIM-120D mod that was added does replace the Bravo variant which happened for all of us.

> Lastly, does this PR supersede this one https://github.com/dcs-liberation/dcs_liberation/pull/3338? If so, I'll go ahead and close that one.

This PR does supersede https://github.com/dcs-liberation/dcs_liberation/pull/3338.

2024-03-04 22:11 UTC, zhexu14 commented
Thanks for the changes @Chilli935 . Unfortunately it looks like the force push (or something else) has deleted some of your commits and some of the YAML changes didn't stick. Can you have a look please? If it's easier, can just close this PR and create a new one.

2024-03-05 07:56 UTC, Chilli935 commented
> Thanks for the changes @Chilli935 . Unfortunately it looks like the force push (or something else) has deleted some of your commits and some of the YAML changes didn't stick. Can you have a look please? If it's easier, can just close this PR and create a new one.

Yeah I was working on some changes in github desktop any way so I'll do that

2024-03-19 10:35 UTC, zhexu14 commented
@Chilli935 FYI I've just tested this branch and everything looks good (at least for someone running without the mod) except possibly a cosmetic change in the New Game Wizard label (it still shows as fa18efg, rather than something like "Super Hornet"). I'm happy to merge this once you're ready.

2024-03-19 13:49 UTC, Chilli935 commented
I think that's all, just checked to make sure and the label is good now so this PR is ready to merge

2024-03-20 20:31 UTC, zhexu14 commented
> I think that's all, just checked to make sure and the label looks good, and did some more testing as someone with the mod which worked well so this PR is ready to merge

Nice one! Which version of the mod did you use?

2024-03-20 20:37 UTC, Chilli935 commented
> > I think that's all, just checked to make sure and the label looks good, and did some more testing as someone with the mod which worked well so this PR is ready to merge
> 
> Nice one! Which version of the mod did you use?

2.2.5, which is the latest version. I was planning to add it in the new game wizard tomorrow morning

2024-03-21 10:04 UTC, Chilli935 commented
@zhexu14 it now contains the mod version in the newgamewizard, so you can go ahead and merge

2024-03-21 10:52 UTC, merged