if aewc is in threat zone move it further away
dcs-liberation/dcs_liberation pull request #896
Opened 2021-02-17 15:50 UTC by siKruger

borrowed from BARCAP generation:

if the AEW&C is in threat zone the waypoint will be moved out of the threat zone

2021-02-18 04:14 UTC, DanAlbert requested changes

2021-02-18 04:14 UTC, DanAlbert commented on gen/flights/flightplan.py
> +                    meters(position.distance(self.threat_zones.all))
This is guaranteed to be zero.

2021-02-18 04:14 UTC, DanAlbert commented on gen/flights/flightplan.py
>          heading = location.position.heading_between_point(closest_airfield.position)
This is still guaranteed to be due north, which isn't necessarily away from the threat.

You might need to play with shapely a bit here, but what you need to do is find a direction that is at least likely to be safer. The BARCAP planning isn't perfect either and just backs away from the closest enemy airfield. That might accidentally back into another enemy airfield if the mission location is surrounded, of course, but it's better than nothing. You could copy that here.

2021-02-18 04:14 UTC, DanAlbert commented on gen/flights/flightplan.py
> +                    - self.doctrine.cap_engagement_range
This distance isn't meaningful here. The reason it was used for the BARCAP planning is that its goal is to keep the edge of the engagement zone out of the enemy threat zone. Here we just need to keep the orbit itself safe. Instead, just pick a larger constant than 5nm. 40nm seems reasonable.

2021-02-18 15:13 UTC, siKruger commented
what do you think of this idea?

basically Iam starting from heading 0 and distance 0 and work my way up to find a point that is outside the threat zone.

In my testing I always got a point outside of the threat zones. sometimes they are not optimal but at least they are outside of any zone

2021-02-19 05:39 UTC, DanAlbert commented
In general we're trying to move away from brute force point searches, as they're slow and might not find an answer at all (we used to have quite of bit of cases that did things like this).

With shapely you should be able to find the closest point on the edge of the threat zone to the target area. Find that point, find the heading from the airfield to that point, and extend on that bearing? (Unless of course the point near the airfield isn't under threat anyway, in which case just use that point).

2021-02-19 15:44 UTC, siKruger commented
> 
> 
> In general we're trying to move away from brute force point searches, as they're slow and might not find an answer at all (we used to have quite of bit of cases that did things like this).
> 
> With shapely you should be able to find the closest point on the edge of the threat zone to the target area. Find that point, find the heading from the airfield to that point, and extend on that bearing? (Unless of course the point near the airfield isn't under threat anyway, in which case just use that point).

Will take a look at this!

2021-02-19 19:47 UTC, siKruger commented
I am now searching for the closest boundary point. 

theoretically they are still inside the threat zone, but if we would move them further away they could end up in another threat zone and i guess then we would be back at out old friend mr bruteforce.

should we risk it and move the point further away or just leave it as it is right now?

2021-02-24 06:31 UTC, DanAlbert approved these changes
Suggested a few cleanups. You should be able to merge this yourself now, and aside from the few nits this looks good so feel free to do so :)

I think we may want to buffer the boundary point a bit, but happy to have this merge as-is and so we can start getting some testing on it.

2021-02-24 06:31 UTC, DanAlbert commented on gen/flights/flightplan.py
> +            return location.position.point_from_heading(heading, 0)
`return location` and remove L1189?

2021-02-24 06:31 UTC, DanAlbert commented on gen/flights/flightplan.py
> +        if meters(position.distance(self.threat_zones.all)) == meters(0):
`if self.threat_zones.threatened(position)`

If you do that you also don't need to explicitly make the `ShapelyPoint`, it'll accept `location.position` so you can delete L1188-L1190.

2021-02-24 06:31 UTC, DanAlbert commented on gen/flights/flightplan.py
> +            closest_closest_boundary = self.threat_zones.closest_boundary(position)
`closest_boundary`, not `closest_closest_boundary` :)

2021-02-24 21:14 UTC, merged